# Generated by Django 5.2 on 2025-05-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('arrays', 'Arrays'), ('linked_list', 'Linked List'), ('two_pointers', 'Two Pointers'), ('oop_inheritance', 'OOP - Inheritance')], default='arrays', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='year_asked',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
