# Generated by Django 5.2.1 on 2025-05-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0004_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='custom_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
