# Generated by Django 5.2.1 on 2025-05-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0006_auto_20250514_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='max_score',
        ),
        migrations.AddField(
            model_name='question',
            name='constraints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='testcase_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
